version: '3'

tasks:
  default:
    deps:
      - task: compile
  tangle:
    cmds:
      - |
       emacs -Q --batch --eval \
         "
         (progn
           (setq debug-on-error t)
           (setq vc-handled-backends nil)
           (require 'ob-tangle)
           (org-babel-tangle-file \"./early-init.org\" \"./early-init.el\" \"emacs-lisp\")
           (org-babel-tangle-file \"./init.org\" \"./init.el\" \"emacs-lisp\")
           (byte-compile-file \"./early-init.el\"))
         "

  compile:
    deps:
      - task: tangle
    cmds:
      - emacs -Q --batch -f batch-byte-compile early-init.el
      - emacs -Q --batch -f batch-byte-compile init.el
    silent: true
